[package]
name = "video-cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
ffmpeg-next = { version = "6.0.0", features = ["static", "build"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
vsprintf = "2.0.0"
